### ISSUE TITLE
Anew Module Error

### ISSUE THREAD

**Issue by secfb** [dwisiswant0/unew#3]
Does the app only work on url data?

<img width="169" alt="image" src="https://user-images.githubusercontent.com/38748801/184102684-99d017d6-dedb-4c82-8728-4be3497e37f4.png">

It does not do what the original anew tool did.
<img width="199" alt="image" src="https://user-images.githubusercontent.com/38748801/184103306-b454bb67-ec89-4237-8fc2-0c7f861f49ce.png">

**Comment by dwisiswant0** [comment]
> Does the app only work on url data?

Yes.
